### ISSUE TITLE
Use the Python "qrencode" library

### ISSUE THREAD

**Issue by mgax** [hoover/search#21]
Right now, we shell out to call the `qrencode` command, when we could use a Python library, [qrencode](https://pypi.python.org/pypi/qrcode/).

**Comment by raduklb** [comment]
The same issue was adressed by [this](https://github.com/liquidinvestigations/core/pull/67) Pull Request on `liquidinvestigations/core` repo and was merged. Please test it and possibly merge the Pull Request which solves the issue on this repo.
